### ISSUE TITLE
npm run build throws Error: Cannot find module 'worker_threads'

### ISSUE THREAD

**Issue by tkoop** [yyx990803/vue-wordle#5]
I'm trying to install this package.  This is what I run:

```
git clone https://github.com/yyx990803/vue-wordle.git
cd vue-wordle
npm install
npm run build
```

This is what that last command outputs:

```
> vue-wordle@0.0.0 build
> vite build

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/www/vue-wordle/node_modules/vite/dist/node/chunks/dep-f5552faa.js:25:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

```

**Comment by yyx990803** [comment]
Your Node version is too old. Upgrade to 16.
